apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql
      tier: database
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
        - image: 'postgres:latest'
          name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom :
                secretKeyRef :
                  name : postgresql-secrets
                  key :  username
            - name: POSTGRES_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : postgresql-secrets
                  key :  password
            - name: POSTGRES_DB
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    tier: database
  clusterIP: None